# Generated by Django 3.0 on 2020-12-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
